# Generated by Django 5.2.11 on 2026-02-14 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("access_token", models.TextField(blank=True, default="")),
                ("category", models.CharField(blank=True, default="", max_length=255)),
                ("about", models.TextField(blank=True, default="")),
                ("fan_count", models.IntegerField(default=0)),
                ("link", models.URLField(blank=True, default="", max_length=500)),
                (
                    "picture_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("tasks", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "name"],
            },
        ),
    ]
