# Generated by Django 5.2.11 on 2026-02-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facebookpage",
            name="link",
            field=models.URLField(blank=True, default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="facebookpage",
            name="picture_url",
            field=models.URLField(blank=True, default="", max_length=2000),
        ),
    ]
