# Dashboard page writer
path = "frontend/app/(dashboard)/dashboard/page.tsx"
out = open(path, "w", newline="
", encoding="utf-8")
W = out.write
W('"use client";\n')
W('\n')
W('import { useState, useEffect } from "react";\n')
W('import { useAuth } from "@/lib/auth";\n')
W('import api from "@/lib/api";\n')
W('import type { FacebookPage, Post } from "@/lib/types";\n')
W('import {\n')
W('  Globe,\n')
W('  FileText,\n')
W('  Users,\n')
W('  TrendingUp,\n')
W('  ArrowUpRight,\n')
W('  Clock,\n')
W('  CheckCircle,\n')
W('  CalendarClock,\n')
W('} from "lucide-react";\n')
W('import Link from "next/link";\n')
W('\n')
W('export default function DashboardPage() {\n')
W('  const { user } = useAuth();\n')
W('  const [pages, setPages] = useState<FacebookPage[]>([]);\n')
W('  const [posts, setPosts] = useState<Post[]>([]);\n')
W('  const [loadingData, setLoadingData] = useState(true);\n')
W('\n')
W('  useEffect(() => {\n')
W('    Promise.all([\n')
W('      api.get("/pages/").catch(() => ({ data: [] })),\n')
W('      api.get("/posts/").catch(() => ({ data: [] })),\n')
W('    ]).then(([pagesRes, postsRes]) => {\n')
W('      const pageList = pagesRes.data.results || pagesRes.data;\n')
W('      const postList = postsRes.data.results || postsRes.data;\n')
W('      setPages(Array.isArray(pageList) ? pageList : []);\n')
W('      setPosts(Array.isArray(postList) ? postList : []);\n')
W('      setLoadingData(false);\n')
W('    });\n')
W('  }, []);\n')
W('\n')
W('  const totalFans = pages.reduce((sum, p) => sum + (p.fan_count || 0), 0);\n')
W('  const publishedPosts = posts.filter((p) => p.status === "published").length;\n')
W('  const scheduledPosts = posts.filter((p) => p.status === "scheduled").length;\n')
W('  const recentPosts = posts.slice(0, 6);\n')
W('\n')
W('  const stats = [\n')
W('    {\n')
W('      label: "Connected Pages",\n')
W('      value: pages.length,\n')
W('      icon: Globe,\n')
W('      gradient: "from-emerald-500 to-teal-600",\n')
W('      iconBg: "bg-primary-light",\n')
W('      href: "/pages",\n')
W('    },\n')
W('    {\n')
W('      label: "Total Followers",\n')
W('      value: totalFans.toLocaleString(),\n')
W('      icon: Users,\n')
W('      gradient: "from-blue-500 to-indigo-600",\n')
W('      iconBg: "bg-info-light",\n')
W('      href: "/pages",\n')
W('    },\n')
W('    {\n')
W('      label: "Published Posts",\n')
W('      value: publishedPosts,\n')
W('      icon: CheckCircle,\n')
W('      gradient: "from-violet-500 to-purple-600",\n')
W('      iconBg: "bg-purple-500/10",\n')
W('      href: "/posts",\n')
W('    },\n')
W('    {\n')
W('      label: "Scheduled",\n')
W('      value: scheduledPosts,\n')
W('      icon: CalendarClock,\n')
W('      gradient: "from-amber-500 to-orange-600",\n')
W('      iconBg: "bg-warning-light",\n')
W('      href: "/scheduler",\n')
W('    },\n')
W('  ];\n')
W('\n')
W('  const initials = user?.first_name\n')
W('    ? `${user.first_name[0]}${user.last_name?.[0] || ""}`.toUpperCase()\n')
W('    : user?.username?.[0]?.toUpperCase() || "U";\n')
W('\n')
W('  return (\n')
W('    <div className="space-y-6">\n')
W('      {/* Welcome banner */}\n')
W('      <div className="flex items-center justify-between">\n')
W('        <div className="flex items-center gap-4">\n')
W('          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-primary to-accent text-base font-bold text-white shadow-sm">\n')
W('            {initials}\n')
W('          </div>\n')
W('          <div>\n')
W('            <h1 className="text-2xl font-bold tracking-tight">\n')
W('              Welcome back{user?.first_name ?  : ""}\n')
W('            </h1>\n')
W('            <p className="mt-0.5 text-sm text-text-secondary">\n')
W('              Here&apos;s an overview of your Facebook pages and content\n')
W('            </p>\n')
W('          </div>\n')
W('        </div>\n')
W('        <Link\n')
W('          href="/posts"\n')
W('          className="hidden items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-medium text-white shadow-sm hover:bg-primary-hover sm:flex"\n')
W('        >\n')
W('          <FileText size={15} />\n')
W('          Create Post\n')
W('        </Link>\n')
W('      </div>\n')
W('\n')
W('      {/* Stats */}\n')
W('      {loadingData ? (\n')
W('        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">\n')
W('          {[...Array(4)].map((_, i) => (\n')
W('            <div key={i} className="h-[110px] animate-pulse rounded-2xl border border-card-border bg-card-bg" />\n')
W('          ))}\n')
W('        </div>\n')
W('      ) : (\n')
W('        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">\n')
W('          {stats.map((stat) => (\n')
W('            <Link\n')
W('              key={stat.label}\n')
W('              href={stat.href}\n')
W('              className="group relative overflow-hidden rounded-2xl border border-card-border bg-card-bg p-5 shadow-[var(--card-shadow)] transition-shadow hover:shadow-[var(--card-shadow-hover)]"\n')
W('            >\n')
W('              <div className={`absolute inset-x-0 top-0 h-[2px] bg-gradient-to-r ${stat.gradient}`} />\n')
W('              <div className="flex items-start justify-between">\n')
W('                <div>\n')
W('                  <p className="text-[13px] font-medium text-muted">{stat.label}</p>\n')
W('                  <p className="mt-2 text-3xl font-bold tracking-tight">{stat.value}</p>\n')
W('                </div>\n')
W('                <div className={`flex h-10 w-10 items-center justify-center rounded-xl ${stat.iconBg}`}>\n')
W('                  <stat.icon size={18} className="text-primary" />\n')
W('                </div>\n')
W('              </div>\n')
W('            </Link>\n')
W('          ))}\n')
W('        </div>\n')
W('      )}\n')
