# Generated by Django 5.2.11 on 2026-02-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_type", models.CharField(max_length=100)),
                ("value", models.IntegerField(default=0)),
                ("date", models.DateField()),
                (
                    "period",
                    models.CharField(
                        choices=[("day", "Day"), ("week", "Week"), ("month", "Month")],
                        default="day",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="pages.facebookpage",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "metric_type"],
                "unique_together": {("page", "metric_type", "date", "period")},
            },
        ),
    ]
