# Generated by Django 5.2.11 on 2026-02-14 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0001_initial"),
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook_comment_id", models.CharField(max_length=255, unique=True)),
                (
                    "facebook_post_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "parent_comment_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("from_name", models.CharField(blank=True, default="", max_length=255)),
                ("from_id", models.CharField(blank=True, default="", max_length=100)),
                ("like_count", models.IntegerField(default=0)),
                ("is_reply", models.BooleanField(default=False)),
                ("comment_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="pages.facebookpage",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-comment_time"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook_conversation_id",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "participant_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "participant_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("updated_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="pages.facebookpage",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_time"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook_message_id", models.CharField(max_length=255, unique=True)),
                ("message", models.TextField(blank=True, default="")),
                ("from_name", models.CharField(blank=True, default="", max_length=255)),
                ("from_id", models.CharField(blank=True, default="", max_length=100)),
                ("message_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messaging.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["message_time"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_comment", "New Comment"),
                            ("comment_reply", "Comment Reply"),
                            ("new_message", "New Message"),
                            ("new_like", "New Like"),
                            ("page_mention", "Page Mention"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "reference_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="pages.facebookpage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
